version: 2

updates:

  - package-ecosystem: "gomod"
    directory: "/services/ledger-rest"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/services/ledger-unit"
    schedule:
      interval: "daily"
